# Generated by Django 5.0.3 on 2024-04-02 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_remove_event_date_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
        ),
        migrations.DeleteModel(
            name='EventDate',
        ),
    ]
