# Generated by Django 5.0.3 on 2024-04-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
